require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PaintingsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Painting. As you add validations to Painting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaintingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all paintings as @paintings" do
      painting = Painting.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:paintings)).to eq([painting])
    end
  end

  describe "GET #show" do
    it "assigns the requested painting as @painting" do
      painting = Painting.create! valid_attributes
      get :show, {:id => painting.to_param}, valid_session
      expect(assigns(:painting)).to eq(painting)
    end
  end

  describe "GET #new" do
    it "assigns a new painting as @painting" do
      get :new, {}, valid_session
      expect(assigns(:painting)).to be_a_new(Painting)
    end
  end

  describe "GET #edit" do
    it "assigns the requested painting as @painting" do
      painting = Painting.create! valid_attributes
      get :edit, {:id => painting.to_param}, valid_session
      expect(assigns(:painting)).to eq(painting)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Painting" do
        expect {
          post :create, {:painting => valid_attributes}, valid_session
        }.to change(Painting, :count).by(1)
      end

      it "assigns a newly created painting as @painting" do
        post :create, {:painting => valid_attributes}, valid_session
        expect(assigns(:painting)).to be_a(Painting)
        expect(assigns(:painting)).to be_persisted
      end

      it "redirects to the created painting" do
        post :create, {:painting => valid_attributes}, valid_session
        expect(response).to redirect_to(Painting.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved painting as @painting" do
        post :create, {:painting => invalid_attributes}, valid_session
        expect(assigns(:painting)).to be_a_new(Painting)
      end

      it "re-renders the 'new' template" do
        post :create, {:painting => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested painting" do
        painting = Painting.create! valid_attributes
        put :update, {:id => painting.to_param, :painting => new_attributes}, valid_session
        painting.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested painting as @painting" do
        painting = Painting.create! valid_attributes
        put :update, {:id => painting.to_param, :painting => valid_attributes}, valid_session
        expect(assigns(:painting)).to eq(painting)
      end

      it "redirects to the painting" do
        painting = Painting.create! valid_attributes
        put :update, {:id => painting.to_param, :painting => valid_attributes}, valid_session
        expect(response).to redirect_to(painting)
      end
    end

    context "with invalid params" do
      it "assigns the painting as @painting" do
        painting = Painting.create! valid_attributes
        put :update, {:id => painting.to_param, :painting => invalid_attributes}, valid_session
        expect(assigns(:painting)).to eq(painting)
      end

      it "re-renders the 'edit' template" do
        painting = Painting.create! valid_attributes
        put :update, {:id => painting.to_param, :painting => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested painting" do
      painting = Painting.create! valid_attributes
      expect {
        delete :destroy, {:id => painting.to_param}, valid_session
      }.to change(Painting, :count).by(-1)
    end

    it "redirects to the paintings list" do
      painting = Painting.create! valid_attributes
      delete :destroy, {:id => painting.to_param}, valid_session
      expect(response).to redirect_to(paintings_url)
    end
  end

end
